# Generated by Django 3.2.9 on 2021-11-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='bairro',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='numero',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='estado',
            new_name='state',
        ),
    ]
