# Generated by Django 3.2.9 on 2021-11-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211101_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
